### ISSUE TITLE
nil printed on every trigger

### ISSUE THREAD

**Issue by rwkiii** [simenkid/lua-events#2]
Wow, I really like using lua-events. I use it as a catch-all and it works great. This and your nodemcu-timer can save a lot of coding and help simplify logic flow. They're forcing me to write memory-smart code, but that's the nature of Lua...

I have a question though. Almost every time an event is fired I get 'nil' printed to the serial console. I'm happy to show you code if this doesn't ring a bell. I suspect it's not a bug but rather normal behavior?

The nil seems to be printed after the code contained in each trigger (hub:on(....))

It doesn't cause a problem, but it's not wanted in the display output.

Thank you for making this code available. It's excellent!

**Comment by simenkid** [comment]
Hello Robert~ Thanks for your feedback. I guess you were grabbing a hub from the minified **events_min.lua**? If you were, the 'nil' thing is my fault. I forgot to comment out the debug printing. I've taken that 'nil' thing off, you can try it again. If the same problem occurs, please let me know.
